Repository walmartlabs/concord, pull requests merged in 2020-09, with the labels that each got.

#124 concord-server: support for added/removed/modified files in github push trigger conditions
  it/server/src/test/java/com/walmartlabs/concord/it/server/GitHubTriggersV2IT.java
  it/server/src/test/resources/com/walmartlabs/concord/it/server/githubTests/repos/v2/files/concord.yml
  server/impl/src/main/java/com/walmartlabs/concord/server/events/github/Constants.java
  server/impl/src/main/java/com/walmartlabs/concord/server/events/github/GithubTriggerV2Processor.java
  server/impl/src/main/java/com/walmartlabs/concord/server/events/github/Payload.java
Labels: docs, wip

#125 server: configurable out variables mode for project
  console2/src/api/org/project/index.ts
  console2/src/components/organisms/ProjectActivity/ProjectSettings.tsx
  console2/src/components/organisms/ProjectOutVariablesModeActivity/index.tsx
  console2/src/components/organisms/index.ts
  it/server/src/test/java/com/walmartlabs/concord/it/server/OutVariablesProjectIT.java
  server/db/src/main/resources/com/walmartlabs/concord/server/db/liquibase.xml
  server/db/src/main/resources/com/walmartlabs/concord/server/db/v1.66.0.xml
  server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectDao.java
  server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectEntry.java
  server/impl/src/main/java/com/walmartlabs/concord/server/org/project/ProjectManager.java
  server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/NewProcessPipeline.java
  server/impl/src/main/java/com/walmartlabs/concord/server/process/pipelines/processors/AssertOutVariablesProcessor.java
  server/impl/src/test/java/com/walmartlabs/concord/server/process/pipelines/processors/ConfigurationProcessorTest.java
  server/impl/src/test/java/com/walmartlabs/concord/server/security/secret/SecretDaoTest.java
  server/impl/src/test/java/com/walmartlabs/concord/server/template/ProjectDaoTest.java
Labels: docs, wip

#129 fix iteritems to items for py2-py3 compatibility
  it/server/src/test/resources/com/walmartlabs/concord/it/server/ansibleVault/get_password.py
  it/server/src/test/resources/com/walmartlabs/concord/it/server/ansibleVaultMultiplePasswordFiles/get_all_password.py
  it/server/src/test/resources/com/walmartlabs/concord/it/server/ansibleVaultMultiplePasswordFiles/get_local_password.py
  plugins/tasks/ansible/src/main/resources/com/walmartlabs/concord/plugins/ansible/lib/task_policy.py
Labels: wip

#143 resource-tasks: implement prettyPrintYaml method
  plugins/tasks/resource/pom.xml
  plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/ResourceTask.java
  plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/ResourceTaskCommon.java
  plugins/tasks/resource/src/main/java/com/walmartlabs/concord/plugins/resource/v2/ResourceTaskV2.java
  plugins/tasks/resource/src/test/java/com/walmartlabs/concord/plugins/resource/ResourceTaskCommonTest.java
Labels: docs
